config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root                            to: "main#index"
  post "/user/update",            to: "user#update"
  get "/auth/:provider/callback", to: "sessions#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/config.rb
class Config < ApplicationRecord

  before_create :ensure_single_config

  def self.main
    Config.first
  end

  private

  def ensure_single_config
    throw(:abort) if Config.exists?
  end

end

app/models/user.rb
class User < ApplicationRecord

  before_save do
    self.color = :white if self.color.nil?

    if self.image_url.present? && self.image_url.ends_with?("_normal.jpg")
      self.image_url = self.image_url.sub("_normal", "_400x400")
    end
  end

  enum color: {
    red:      1,
    green:    2,
    blue:     3,
    yellow:   4,
    cyan:     5,
    magenta:  6,
    white:    7,
    black:    8,
    pink:     9
  }

  def self.colors_mapping
    {
      red: 'rgba(255, 0, 0, 1)',
      green: 'rgba(0, 255, 0, 1)',
      blue: 'rgba(0, 0, 255, 1)',
      yellow: 'rgba(255, 255, 0, 1)',
      cyan: 'rgba(0, 255, 255, 1)',
      magenta: 'rgba(255, 0, 255, 1)',
      white: 'rgba(255, 255, 255, 1)',
      black: 'rgba(0, 0, 0, 1)',
      pink: 'rgba(227, 61, 148, 1)'
    }
  end

  def color_rgb
    colors_mapping[self.color]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_connected?, :current_user

  def current_connected?
    session[:user_id].present? && User.exists?(id: session[:user_id])
  end

  def current_user
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @gpt_phrase = get_random_gpt_phrase
  end

  private

  def get_random_gpt_phrase
    file_path = Rails.root.join('public', 'prompts.txt')
    file_content = File.read(file_path)
    lines = file_content.split("\n")
    random_line = lines.sample
    puts random_line
    random_line
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['nickname']
      u.image_url = auth['info']['image']
    end

    session[:user_id] = user.id
    redirect_to root_path, notice: 'Logged in successfully!'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out successfully!'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :check_current_connected

  def update
    response = { status: 0 }

    if current_user.update(user_params)
      response[:status] = 1
    end

    render json: response
  end

  private

  def check_current_connected
    return unless current_connected?
  end

  def user_params
    params.require(:user).permit(
      :color
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pacmoon Dance</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Pacmoon Dance - The rules are simple: don't cause havok but pressing the button. For real.">
    <meta name="keywords" content="Pacmoon, crypto, cryptocurrency, meme, pacman, shooting stars">
    <meta property="og:title" content="Pacmoon Dance - It's not even a dance, it's just a button.">
    <meta property="og:description" content="The rules are simple: don't cause havok but pressing the button. For real.">
    <meta property="og:image" content="<%= asset_path("screenshot.png") %>">
    <meta property="og:url" content="https://pacmoon-09c1cf1dd6ff.herokuapp.com/">
    <link rel="canonical" href="https://pacmoon-09c1cf1dd6ff.herokuapp.com/">
    <meta name="robots" content="index, nofollow">
    <link rel="icon" href="<%= asset_path("favicon.png") %>" type="image/png">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>

  <%= render partial: "/participants_json" %>
</html>

app/views/main/index.html.erb
<main class="w-full h-screen flex justify-center items-center">
  <canvas id="starryBackground"></canvas>
  <div class="absolute z-10 top-0 left-1/2 transform -translate-x-1/2 bg-white bg-opacity-10 p-3 rounded-lg shadow-lg">
    <div class="flex items-center gap-4">
      <% if current_connected? %>
        <%= image_tag(current_user.image_url, class: "rounded-full max-w-[18px]") %>
      <% end %>
      <a class="cursor-pointer" data-content-target="#main-box">
        <svg id="eye-closed" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512" class="text-yellow-400 h-[20px] w-[20px]" fill="currentColor">
          <!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
          <path d="M38.8 5.1C28.4-3.1 13.3-1.2 5.1 9.2S-1.2 34.7 9.2 42.9l592 464c10.4 8.2 25.5 6.3 33.7-4.1s6.3-25.5-4.1-33.7L525.6 386.7c39.6-40.6 66.4-86.1 79.9-118.4c3.3-7.9 3.3-16.7 0-24.6c-14.9-35.7-46.2-87.7-93-131.1C465.5 68.8 400.8 32 320 32c-68.2 0-125 26.3-169.3 60.8L38.8 5.1zM223.1 149.5C248.6 126.2 282.7 112 320 112c79.5 0 144 64.5 144 144c0 24.9-6.3 48.3-17.4 68.7L408 294.5c8.4-19.3 10.6-41.4 4.8-63.3c-11.1-41.5-47.8-69.4-88.6-71.1c-5.8-.2-9.2 6.1-7.4 11.7c2.1 6.4 3.3 13.2 3.3 20.3c0 10.2-2.4 19.8-6.6 28.3l-90.3-70.8zM373 389.9c-16.4 6.5-34.3 10.1-53 10.1c-79.5 0-144-64.5-144-144c0-6.9 .5-13.6 1.4-20.2L83.1 161.5C60.3 191.2 44 220.8 34.5 243.7c-3.3 7.9-3.3 16.7 0 24.6c14.9 35.7 46.2 87.7 93 131.1C174.5 443.2 239.2 480 320 480c47.8 0 89.9-12.9 126.2-32.5L373 389.9z"/>
        </svg>
        <svg id="eye-opened" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512" class="hidden text-gray-500 h-[20px] w-[20px]" fill="currentColor">
          <!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
          <path d="M288 32c-80.8 0-145.5 36.8-192.6 80.6C48.6 156 17.3 208 2.5 243.7c-3.3 7.9-3.3 16.7 0 24.6C17.3 304 48.6 356 95.4 399.4C142.5 443.2 207.2 480 288 480s145.5-36.8 192.6-80.6c46.8-43.5 78.1-95.4 93-131.1c3.3-7.9 3.3-16.7 0-24.6c-14.9-35.7-46.2-87.7-93-131.1C433.5 68.8 368.8 32 288 32zM144 256a144 144 0 1 1 288 0 144 144 0 1 1 -288 0zm144-64c0 35.3-28.7 64-64 64c-7.1 0-13.9-1.2-20.3-3.3c-5.5-1.8-11.9 1.6-11.7 7.4c.3 6.9 1.3 13.8 3.2 20.7c13.7 51.2 66.4 81.6 117.6 67.9s81.6-66.4 67.9-117.6c-11.1-41.5-47.8-69.4-88.6-71.1c-5.8-.2-9.2 6.1-7.4 11.7c2.1 6.4 3.3 13.2 3.3 20.3z"/>
        </svg>
      </a>
      <a class="cursor-pointer toggle-content-link active" data-content-target="#disclaimer">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="text-yellow-400 h-[18px] w-[18px]" fill="currentColor">
          <!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
          <path d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224a32 32 0 1 0 -64 0 32 32 0 1 0 64 0z"/>
        </svg>
      </a>
      <a class="cursor-pointer toggle-content-link" data-content-target="#info">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="text-yellow-400 h-[18px] w-[18px]" fill="currentColor">
          <!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
          <path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM216 336h24V272H216c-13.3 0-24-10.7-24-24s10.7-24 24-24h48c13.3 0 24 10.7 24 24v88h8c13.3 0 24 10.7 24 24s-10.7 24-24 24H216c-13.3 0-24-10.7-24-24s10.7-24 24-24zm40-208a32 32 0 1 1 0 64 32 32 0 1 1 0-64z"/>
        </svg>
      </a>
      <a class="cursor-pointer toggle-content-link" data-content-target="#settings">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="text-yellow-400 h-[18px] w-[18px]" fill="currentColor">
          <!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
          <path d="M495.9 166.6c3.2 8.7 .5 18.4-6.4 24.6l-43.3 39.4c1.1 8.3 1.7 16.8 1.7 25.4s-.6 17.1-1.7 25.4l43.3 39.4c6.9 6.2 9.6 15.9 6.4 24.6c-4.4 11.9-9.7 23.3-15.8 34.3l-4.7 8.1c-6.6 11-14 21.4-22.1 31.2c-5.9 7.2-15.7 9.6-24.5 6.8l-55.7-17.7c-13.4 10.3-28.2 18.9-44 25.4l-12.5 57.1c-2 9.1-9 16.3-18.2 17.8c-13.8 2.3-28 3.5-42.5 3.5s-28.7-1.2-42.5-3.5c-9.2-1.5-16.2-8.7-18.2-17.8l-12.5-57.1c-15.8-6.5-30.6-15.1-44-25.4L83.1 425.9c-8.8 2.8-18.6 .3-24.5-6.8c-8.1-9.8-15.5-20.2-22.1-31.2l-4.7-8.1c-6.1-11-11.4-22.4-15.8-34.3c-3.2-8.7-.5-18.4 6.4-24.6l43.3-39.4C64.6 273.1 64 264.6 64 256s.6-17.1 1.7-25.4L22.4 191.2c-6.9-6.2-9.6-15.9-6.4-24.6c4.4-11.9 9.7-23.3 15.8-34.3l4.7-8.1c6.6-11 14-21.4 22.1-31.2c5.9-7.2 15.7-9.6 24.5-6.8l55.7 17.7c13.4-10.3 28.2-18.9 44-25.4l12.5-57.1c2-9.1 9-16.3 18.2-17.8C227.3 1.2 241.5 0 256 0s28.7 1.2 42.5 3.5c9.2 1.5 16.2 8.7 18.2 17.8l12.5 57.1c15.8 6.5 30.6 15.1 44 25.4l55.7-17.7c8.8-2.8 18.6-.3 24.5 6.8c8.1 9.8 15.5 20.2 22.1 31.2l4.7 8.1c6.1 11 11.4 22.4 15.8 34.3zM256 336a80 80 0 1 0 0-160 80 80 0 1 0 0 160z"/>
        </svg>
      </a>
    </div>
  </div>
  <div  id="main-box" class="absolute isolate overflow-hidden h-full w-full flex items-center justify-center">
    <div class="bg-white bg-opacity-10 p-4 rounded-lg shadow-lg w-1/2 mx-auto">
      <div class="mb-4">
        <div class="relative text-xs text-gray-500 p-8 border rounded-lg border-yellow-400">
          <div class="content">
            <div id="disclaimer" class="toggle-content">
              <span class="text-yellow-400">Disclaimer</span>
              Do not click. That's it, just don't click.
            </div>
            <div id="info" class="toggle-content hidden">
              <span class="text-yellow-400">Information</span>
              If you ever find this project funny, send some love <a href="https://x.com/sirgmbot" target="_blank" class="text-yellow-100">@sirgmbot</a>. You can also send some hate if you don't.
              <br/>
              Oh, and in case you're feeling supportive today:
              <span class="text-yellow-100">0xF291d7BAD4F553Ff118bDEE2edEFbE378C3154F7</span>
              <br/>
              I might end up using donations to buy some $PAC to become a validator. Or I might just buy some nice cheese. I really like cheese.
            </div>
            <div id="settings" class="toggle-content hidden">
              <span class="text-yellow-400">Settings</span>
                Change a lot of really freaking cool things here. If you're logged in you can do some even cooler stuff.
                <br/>
                I might add some in the future if I feel like it.
                <br/>
                And if you REALLY REALLY want to stop the dance and you didn't know that refreshing your browser could stop it, I got you:
                <br/>
                <%= link_to root_path, class: "text-red-500", data: { turbo: false } do %>
                  Please sirgm, stop !
                <% end %>
                <% if current_connected? %>
                  <br/><br/>
                  <% @colors = ['red', 'green', 'blue', 'yellow', 'purple'] %>
                  <p>You can change your color and see how many people are using it too:</p>
                  <%= form_for :user, url: user_update_path do |f| %>
                    <div class="grid grid-cols-4 gap-2 mt-1">
                      <% User.colors.keys.each do |color| %>
                        <label class="inline-flex flex-col items-center space-y-1 cursor-pointer">
                          <input type="radio" name="color" value="<%= color %>" class="hidden" />
                          <div class="color-choice color-<%= color %> w-10 h-10 rounded-full <%= "border-2 border-yellow-400 ring-2 ring-yellow-400" if current_user.color.eql? color %>" style="background-color: <%= User.colors_mapping[color.to_sym] %>"></div>
                          <span class="text-xs text-gray-500"><%= User.where(color: color).count %></span>
                        </label>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
            </div>
          </div>
        </div>
        <audio id="crazySpinIntroAudio" src="<%= asset_path('intro.mp3') %>"></audio>
        <audio id="crazySpinLoopAudio" src="<%= asset_path('loop.mp3') %>" loop></audio>
      </div>
      <div class="flex items-center justify-center gap-4">
        <button id="startCrazySpin" type="button" class="w-full text-yellow-400 border-yellow-400 hover:bg-yellow-500 border hover:text-white font-medium rounded-lg text-sm px-5 py-2.5 text-center">
          START
        </button>
        <% unless current_connected? %>
          <%= link_to '/auth/twitter2', class: "w-full bg-black hover:bg-yellow-500 font-medium rounded-lg text-sm px-5 py-2.5 text-center" do %>
            <span class="flex items-center justify-center text-white">
              <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 512 512" class="text-white h-5 w-5 mr-2">
                <path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"></path>
              </svg>
              <span>JOIN THE FUN</span>
            </span>
          <% end %>
        <% end %>
      </div>
      <div class="flex items-center justify-between mt-2">
        <a id="twitter-handle" href="https://x.com/pacmoon_" target="_blank" class="text-xs text-yellow-100">@pacmoon_</a>
        <p class="text-xs text-yellow-100">Number of degens: <%= User.count %></p>
      </div>
    </div>
  </div>
  <input type="hidden" id="participants-data" value="">
</main>

<style>
  body, html {
    margin: 0;
    padding: 0;
    width: 100%;
    height: 100%;
    overflow: hidden;
    background-color: black;
  }
  canvas {
    display: block;
  }
   @keyframes slide-down {
      from {
        opacity: 0;
        transform: translateY(-10px);
      }
      to {
        opacity: 1;
        transform: translateY(0);
      }
    }

    @keyframes slide-up {
      from {
        opacity: 1;
        transform: translateY(0);
      }
      to {
        opacity: 0;
        transform: translateY(-10px);
      }
    }

    .animate-slide-down {
      animation: slide-down 0.3s ease-out forwards;
    }

    .animate-slide-up {
      animation: slide-up 0.3s ease-in forwards;
    }

    @keyframes fade-in {
      from {
        opacity: 0;
      }
      to {
        opacity: 1;
      }
    }

    @keyframes fade-out {
      from {
        opacity: 1;
      }
      to {
        opacity: 0;
      }
    }

    .animate-fade-in {
      animation: fade-in 0.3s ease forwards;
    }

    .animate-fade-out {
      animation: fade-out 0.3s ease forwards;
    }
    .toggle-content-link .text-yellow-400 {
      color: rgb(107, 114, 128);
    }
    .toggle-content-link.active .text-yellow-400 {
      color: rgb(250, 204, 21);
    }
</style>